apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco-daemonset
  labels:
    app: falco-example
    role: security
spec:
  selector:
    matchLabels:
      app: falco-example
      role: security
  template:
    metadata:
      labels:
        app: falco-example
        role: security
    spec:
      hostPID: true
      serviceAccount: falco-account
      initContainers:
        - name: falco-driver-loader
          image: falcosecurity/falco-driver-loader:0.23.0
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /root/.falco
              name: root-falco
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/etc/
              name: etc-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
      containers:
        - name: falco-no-driver
          image: falcosecurity/falco-no-driver:0.23.0
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          args:
            - "/usr/bin/falco"
            - "--cri"
            - "/run/containerd/containerd.sock"
            - "-K"
            - "/var/run/secrets/kubernetes.io/serviceaccount/token"
            - "-k"
            - "https://$(KUBERNETES_SERVICE_HOST)"
            - "-pk"
          volumeMounts:
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            - mountPath: /etc/falco
              name: falco-config
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: root-falco
          hostPath:
            path: /root/.falco
        - name: falco-config
          configMap:
            name: falco-config
